### ISSUE TITLE
Make it more Responsive

### ISSUE THREAD

**Issue by Vedantk6403** [Ananta-Vaishnavi/Portfolio#6]
The Website is not responsive on desktop layout. Need to change some CSS.

**Comment by Vedantk6403** [comment]
Shall I work on it. Please assign it to me.

**Comment by Ananta-Vaishnavi** [comment]
I appreciate your contribution to our project! Thank you for taking the time to contribute and for showing your support for our community. I value your efforts and look forward to seeing more contributions from you in the future.
